application: networkxd3
version: 5-0-4
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: django
  version: "1.4"

inbound_services:
- warmup

handlers:

- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin
  secure: always

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application
  secure: always

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/
  static_dir: static
  expiration: '0'

- url: /(_ah|cron)/.*
  script: networkx.wsgi.application
  login: admin
  secure: always

- url: /.*
  script: networkx.wsgi.application
  secure: always

- url: /static
  static_dir: static
  expiration: '1m'

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

skip_files:
- ^(.*/)?app.yaml
- ^(.*/)?app.yml
- ^(.*/)?index.yaml
- ^(.*/)?index.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- tmp
